name: CI

on:
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

# Global environment variables for cache optimization
env:
  GO_VERSION: '1.22'  # Primary Go version for caching
  GO_CACHE_VERSION: v1  # Increment this to bust all caches if needed

jobs:
  # Cache setup job - runs once and shares cache across all other jobs
  setup:
    name: Setup Dependencies
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Cache Go modules and build cache
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ env.GO_CACHE_VERSION }}-${{ hashFiles('**/go.sum', '**/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ env.GO_CACHE_VERSION }}-

    - name: Download dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        go mod download
        go mod verify

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        go-version: ['1.21', '1.22']
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    # Only restore cache for the primary version, others will download fresh
    - name: Restore Go cache
      if: matrix.go-version == env.GO_VERSION
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ env.GO_CACHE_VERSION }}-${{ hashFiles('**/go.sum', '**/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ env.GO_CACHE_VERSION }}-

    - name: Download dependencies
      if: matrix.go-version != env.GO_VERSION
      run: |
        go mod download
        go mod verify

    - name: Check go mod tidy
      run: |
        go mod tidy
        git diff --exit-code go.mod go.sum
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check gofmt
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "Code is not properly formatted. Please run 'gofmt -s -w .'"
          gofmt -s -l .
          exit 1
        fi

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        go-version: ['1.21', '1.22']
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    # Only restore cache for the primary version, others will download fresh
    - name: Restore Go cache
      if: matrix.go-version == env.GO_VERSION
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ env.GO_CACHE_VERSION }}-${{ hashFiles('**/go.sum', '**/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ env.GO_CACHE_VERSION }}-

    - name: Download dependencies
      if: matrix.go-version != env.GO_VERSION
      run: |
        go mod download
        go mod verify

    - name: Build
      run: go build -v ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        go-version: ['1.21', '1.22']
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    # Only restore cache for the primary version, others will download fresh
    - name: Restore Go cache
      if: matrix.go-version == env.GO_VERSION
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ env.GO_CACHE_VERSION }}-${{ hashFiles('**/go.sum', '**/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ env.GO_CACHE_VERSION }}-

    - name: Download dependencies
      if: matrix.go-version != env.GO_VERSION
      run: |
        go mod download
        go mod verify

    - name: Run tests
      run: go test -v -race -coverprofile=coverage.out ./...

    - name: Check test coverage
      run: |
        go tool cover -func=coverage.out
        COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
        echo "Total coverage: ${COVERAGE}%"
        # Check if coverage is at least 75% (as per project guidelines)
        COVERAGE_INT=$(echo "$COVERAGE" | awk '{print int($1)}')
        if [ "$COVERAGE_INT" -lt 75 ]; then
          echo "Test coverage is below 75% threshold. Current coverage: ${COVERAGE}%"
          exit 1
        fi

    # Only upload coverage from primary Go version to avoid duplicate reports
    - name: Upload coverage to Codecov
      if: matrix.go-version == env.GO_VERSION
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.out
        fail_ci_if_error: false
        verbose: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}